version: "3.3"

services:
  database:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=test
